### ISSUE TITLE
Sliding Window

### ISSUE THREAD

**Issue by echefcy** [stevemandl/meter-anomaly-cron#21]
Made an initial implementation of the sliding window algorithm, using MLP as regressor. 

Explanation: look at the last k measurements, make a prediction of the next measurement based on that. Make confidence intervals for the predictions, if the actual next measurement falls outside of the confidence interval we label it as an outlier. 

Advantages:
- Very flexible technique! You can swap out regressors and define different confidence margins very easily. I've only made a point-wise outlier detector for right now but I can see it easily being adapted for trend-wise
- Seems to be decent on initial testing, though more tests needs to be done to make any conclusions
- Very simple

Additional work
- Make a better confidence interval
- Bag MLPs to reduce regressor variance
- Data cleaning/generation
- Test out other regressors

**Comment by echefcy** [comment]
I've also refactored the codebase a little. All the implemented algorithms are in python_lib. I also made a separate experiments folder to test the algorithms.

**Comment by deuterium1729** [comment]
Sounds good. I will make one for isolation forest and 1 class SVM
